Write unit testing
rica213/school-library pull request #9
Opened 2023-04-27 14:46 UTC by rica213

In this milestone, here are what we have done:
- Write unit tests to all the classes : Books, Person, Teacher, Student, Classroom, and Rental
- Update readme file accordingly

2023-04-27 14:57 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @rica213 and @shaaibu7,

Good job so far!
✔️ All tests are passing
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 14:57 UTC, TedLivist commented on README.md
> +- **Implement unit tests.**
- [ ] Kindly add tests for the capitalize and trimmer decorator classes.

2023-04-28 08:14 UTC, zieeco approved these changes
# status: APPROVED :green_circle: :100: 

Hi, @rica213, 

<img height="130" src="https://media1.giphy.com/media/FyH83LEK2hytq/giphy.gif"/>


Good job so far 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⚡
 
✅ Descriptive PR 👍 
✅ Good commit messages 👍 
✅ Linters are passing 👏 


## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 08:24 UTC, rica213 commented
@TedLivist , @zieeco 

Thank you for taking the time in reviewing our project. We are grateful for your hard work, and your insights on how to improve our code. 🙇🏼‍♀️

2023-04-28 08:24 UTC, merged